package cmd

const (
	// cmdConfigList 配置列表命令
	cmdConfigList = "configList"
	// cmdConfigSetting 配置设置命令
	cmdConfigSetting = "configSetting"
	// cmdAppList app列表
	cmdAppList = "appList"
	// cmdAppListByAppName 根据名称查看app详细信息
	cmdAppListByAppName = "appListByAppName"
	// cmdAppListByAppNameAndVersion 根据名称和版本号查询app详情
	cmdAppListByAppNameAndVersion = "appListByAppNameAndVersion"
	// cmdStart 启动命令
	cmdStart = "start"
	// cmdStartWithConfig 根据启动配置文件进行启动
	cmdStartWithConfig = "startWithConfig"
	// cmdPsApp 查看应用当前进程
	cmdPsApp = "psApp"
	// cmdPsAppPlugin 查看应用当前插件信息以及输出
	cmdPsAppPlugin = "psAppPlugin"
	// cmdPsList 查看进程列表
	cmdPsList = "psList"
	// cmdStop 停止应用
	cmdStop = "stop"
	// cmdStopWithConfig 停止伴随应用配置文件
	cmdStopWithConfig = "stopWithConfig"
	// cmdRmAll 删除所有
	cmdRmAll = "rmAll"
	// cmdRmByName 删除根据名称
	cmdRmByName = "rmByName"
	// cmdRmByNameAndVersion 删除根据名称和版本
	cmdRmByNameAndVersion = "rmByNameAndVersion"
	// cmdLogByName 日志通过应用名称
	cmdLogByName = "logByName"
	// cmdLogByNameAndVersion 日志通过app名称和版本
	cmdLogByNameAndVersion = "logByNameAndVersion"
	// cmdSyncInfo 同步信息
	cmdSyncInfo = "syncInfo"
	// cmdRestart 重启
	cmdRestart = "restart"
	// cmdRestartWithConfig 重启跟随配置文件
	cmdRestartWithConfig = "restartWithConfig"
	// cmdJdkLs jdk查询列表
	cmdJdkLs = "jdkLs"
	// cmdJdkLsName jdk查询单个详情
	cmdJdkLsName = "jdkLsName"
	// cmdJdkRm jdk删除
	cmdJdkRm = "jdkRm"
	// cmdJdkRmAll jdk删除所有
	cmdJdkRmAll = "jdkRmAll"
	// cmdJdkRename jdk重命名
	cmdJdkRename = "jdkRename"
	// cmdInfo 详情
	cmdInfoBanner = "infoBanner"
	// cmdInfoLogClear 日志清除
	cmdInfoLogClear = "infoLogClear"
	// cmdExport 导出
	cmdExport = "export"
)
